Fix a lot of English typos (using Microsoft Word)
GregTechCEu/gregicality-skyblock-edition pull request #13
Opened 2021-02-15 23:15 UTC by CrafterKolyan

2021-02-15 23:20 UTC, huneau commented
nice job :)

2021-02-15 23:20 UTC, huneau commented
@Irgendwer01 Can I merge?

2021-02-21 13:56 UTC, Irgendwer01 commented
@huneau @CrafterKolyan Does the Configs got tested? Because it could be that the Configs will just be replaced at load because of the changes

2021-02-21 14:44 UTC, CrafterKolyan commented
> @huneau @CrafterKolyan Does the Configs got tested? Because it could be that the Configs will just be replaced at load because of the changes

I don't think it does really matter. There are not a lot of people looking at the configs of modpack.

2021-02-21 17:02 UTC, CrafterKolyan commented
And actually comments in configs are not looked at Minecraft at all. Even if the comment in mod is different nothing will change and everything will be working.

2021-02-21 17:25 UTC, huneau commented
@Irgendwer01 No idea if the config is reload if comment are updated

2021-03-28 03:43 UTC, brachy84 requested changes
After some testing I found out that configs get reloaded. I'm not sure if changed values get reloaded, but the comments get reloaded. Please remove the changes on config comments

2021-03-28 03:43 UTC, brachy84 commented on config/exnihilocreatio/ExNihiloCreatio.cfg
> -        # Enable this to to load the JSON files.
please, undo this change

2021-03-28 03:43 UTC, brachy84 commented on config/forestry/common.cfg
> -        # The format power will be displayed in in engine/machine interfaces. [default: RF] [valid: [RF, FE, MJ, TESLA]]
undo this change

2021-03-28 03:43 UTC, brachy84 commented on config/opencomputers/settings.conf
> -  # File system related settings, performance and and balancing.
also undo this

2021-03-28 03:43 UTC, brachy84 commented on config/opencomputers/settings.conf
> -    # called a byte array with the specified size has to be allocated. So if
and this

2021-03-28 03:43 UTC, brachy84 commented on config/opencomputers/settings.conf
> -    # to the addresses / address ranges in this list. It it is present in this
and this

2021-03-28 03:43 UTC, brachy84 commented on config/opencomputers/settings.conf
> -    # a value of 10, gold ingots a value of 5 and and diamonds a value of 3.
and this

2021-03-28 03:43 UTC, brachy84 commented on config/opencomputers/settings.conf
> -      # bonus is halved for the second neighbor. So three capacitors in a
and this

2021-03-28 03:43 UTC, brachy84 commented on config/opencomputers/settings.conf
> -    # going into the block. So if a redstone signal of eight is set, it'll
and this

2021-03-28 03:43 UTC, brachy84 commented on config/opencomputers/settings.conf
> -    # generate as much energy as you'd get by burning  fuel in a BuildCraft
and this

2021-03-28 03:43 UTC, brachy84 commented on config/opencomputers/settings.conf
> -      # internal buffer for each level it gains. So with the default values,
and this

2021-03-28 03:43 UTC, brachy84 commented on config/opencomputers/settings.conf
> -      # durability when used, relative to the base rate. So for example, a
and this

2021-03-28 03:43 UTC, brachy84 commented on config/rftools/rftools.cfg
> -    # RF per tick that the the booster can receive [range: 0 ~ 2147483647, default: 1000]
and this

2021-03-28 03:43 UTC, brachy84 commented on config/rftools/rftools.cfg
> -    # RF per tick that the the environmental controller can receive [range: 0 ~ 2147483647, default: 20000]
and this

2021-03-28 03:43 UTC, brachy84 commented on config/rftools/rftools.cfg
> -    # RF per tick that the the screen controller can receive [range: 0 ~ 2147483647, default: 1000]
and this

2021-03-28 03:43 UTC, brachy84 commented on config/rftools/rftools.cfg
> -    # RF per tick that the the charged porter item can receive [range: 0 ~ 2147483647, default: 2000]
and this

2021-03-28 06:54 UTC, hjae78 commented on config/exnihilocreatio/ExNihiloCreatio.cfg
> -        # Enable this to to load the JSON files.
How come?

2021-03-28 07:01 UTC, brachy84 commented on config/exnihilocreatio/ExNihiloCreatio.cfg
> -        # Enable this to to load the JSON files.
as i said above. it reloads the file.

2021-03-28 14:07 UTC, a-thoren commented on config/exnihilocreatio/ExNihiloCreatio.cfg
> -        # Enable this to to load the JSON files.
Ah okay, didn't see that comment

2021-03-28 18:10 UTC, CrafterKolyan commented on config/exnihilocreatio/ExNihiloCreatio.cfg
> -        # Enable this to to load the JSON files.
Reverted all cfg files

2021-03-28 18:29 UTC, brachy84 approved these changes

2021-04-05 04:32 UTC, merged